version: '3'

services:
  db:
    image: postgres:9.6
    command: ["postgres"]
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5435:5432
