# Generated by Django 2.2.6 on 2019-10-20 20:54

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html',
        ),
        migrations.AlterField(
            model_name='post',
            name='markdown',
            field=martor.models.MartorField(verbose_name='Text'),
        ),
    ]
